name: testExercice2
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm testStats
      - run: ls
      - run: jq .stats.passPercent mochawesome-report/mochawesome-report.json
