name: testExercice2
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run testStats && jq .stats.passPercent mochawesome-report/mochawesome.json
  gsheet:
    runs-on: ubuntu-latest
    needs: test_pull_request
    steps:
      - id: "reading"
      - uses: actions/checkout@master
        name: Set env
        run: |
          ls 
          echo ::set-env name=GRADE:: jq .stats.passPercent mochawesome-report/mochawesome.json
      - id: "grading"
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: ${{ secrets.TEST_SPREADSHEET_ID }}
          commands: |
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "Sheet1" }},
              { "command": "updateData", "args": { "data": [[],[,$GRADE] }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
          
