name: test
  on:
    pull_request: 
      branches: [master]
  jobs:
    test_pull_request:
      run-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 13
        - run: npm ci
        - run: npm test

      
    