name: testExercice2
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run testStats && jq .stats.passPercent mochawesome-report/mochawesome.json || npm run testStats || jq .stats.passPercent mochawesome-report/mochawesome.json
  gsheet:
    runs-on: ubuntu-latest
    needs: test_pull_request
    steps:
      - id: "grading"
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: |
            -----BEGIN PRIVATE KEY-----
            dhiaweslati16@gmail.com
            -----END PRIVATE KEY-----

          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "testi" }},
              { "command": "updateData", "args": { "data": [["A1", "A2", "A3"]] }},
              { "command": "appendData", "args": { "data": [["B1", "B2", "B3"]], "minCol": 1 }},
              { "command": "appendData", "args": { "data": [["C2", "C3", "C4"]], "minCol": 2 }},
              { "command": "getData", "args": { "minCol": 1 } },
              { "command": "getData", "args": { "range": "testi!A2:B3" } },
              { "command": "removeWorksheet", "args": { "worksheetTitle": "testi" }}
            ]
        env:
<<<<<<< HEAD
          GSHEET_CLIENT_EMAIL: |
            -----BEGIN PRIVATE KEY-----
            AIzaSyCUoKdEm0_ZE0QOfSLjgURtS4aVpJM1d7U
            -----END PRIVATE KEY-----

          GSHEET_PRIVATE_KEY: |
            -----BEGIN PRIVATE KEY-----
            1fbyH1UrlX8ZWXDJQ41Z-3jMBL3zMSaZDti3KtB6k2zc
            -----END PRIVATE KEY-----
            
=======
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
>>>>>>> 14334815d883200be2a24181c8c72d89a6ccdf13
