name: testExercice2
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      # - run: npm run testStats && jq .stats.passPercent mochawesome-report/mochawesome.json
      - run: npm run testStats
  grade:
    runs-on: ubuntu-latest
    needs: test_pull_request
    steps:
      - uses: actions/checkout@v2
      - run: jq .stats.passPercent mochawesome-report/mochawesome.json
