name: testExercice2
on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run testStats && jq .stats.passPercent mochawesome-report/mochawesome.json || npm run testStats || jq .stats.passPercent mochawesome-report/mochawesome.json
  gsheet:
    runs-on: ubuntu-latest
    needs: test_pull_request
    steps:
      - id: "grading"
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: 1fbyH1UrlX8ZWXDJQ41Z-3jMBL3zMSaZDti3KtB6k2zc
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "testi" }},
              { "command": "updateData", "args": { "worksheetTitle": "test sheet", "data": [["A1", "A2", "A3"]] }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
